export const ALL_KBS = [
  {
    id: '1',
    title: '客服智能问答知识库',
    industry: '通用',
    tags: ['客服', '问答', 'FAQ', '话术'],
    author: '小浣熊官方',
    avatar: '🦝',
    docCount: 186,
    fileTypes: ['Word', 'PDF', 'Markdown'],
    saves: 3421,
    views: 12860,
    likes: 624,
    createdAt: '2周前',
    updatedAt: '1天前',
    isOfficial: true,
    desc: '覆盖售前咨询、售后服务、投诉处理等场景的完整客服知识库。转存后，在小浣熊中 @ 本知识库，即可让 AI 自动回答用户问题，无需人工逐条查找。',
    preview: [
      '产品常见问题 FAQ.docx',
      '退换货处理流程.pdf',
      '投诉处理话术手册.docx',
      '会员权益说明.pdf',
      '售后服务标准 SOP.docx',
      '客服绩效考核指引.xlsx',
    ],
    usagePattern: '@客服知识库 用户反映订单长时间未发货，请帮我起草一封安抚邮件',
    linkedChains: ['工单自动分类链路', '客户满意度分析链路'],
    pawSteps: ['Plan：识别用户问题类型', 'Analyze：检索知识库对应政策', 'Write：生成标准回复话术'],
  },
  {
    id: '2',
    title: '合同审查与风险识别库',
    industry: '法律',
    tags: ['合同', '风险', '合规', '法务'],
    author: '李律师',
    avatar: 'L',
    docCount: 214,
    fileTypes: ['PDF', 'Word'],
    saves: 1986,
    views: 7240,
    likes: 348,
    createdAt: '3周前',
    updatedAt: '3天前',
    isOfficial: false,
    desc: '收录了劳动合同、采购合同、服务协议等 20+ 种合同模板及对应的风险条款识别指南。配合小浣熊链路，可实现合同上传后自动标注高风险条款并给出修改建议。',
    preview: [
      '劳动合同风险条款清单.docx',
      '采购合同审查要点.pdf',
      '保密协议 NDA 标准版.docx',
      '股权投资协议模板.docx',
      '服务合同违约条款说明.pdf',
      '合同合规自查 Checklist.xlsx',
    ],
    usagePattern: '@合同知识库 分析这份采购合同中哪些条款对我方不利，给出修改建议',
    linkedChains: ['合同风险审查链路', '合规条款对比链路'],
    pawSteps: ['Plan：确定合同类型和审查重点', 'Analyze：逐条对照知识库风险标准', 'Write：生成风险报告及修改建议'],
  },
  {
    id: '3',
    title: '产品需求文档资源库',
    industry: '互联网',
    tags: ['PRD', '需求', '产品设计', 'UX'],
    author: '产品团队',
    avatar: 'P',
    docCount: 167,
    fileTypes: ['Word', 'Markdown', 'PDF'],
    saves: 2134,
    views: 8960,
    likes: 412,
    createdAt: '1周前',
    updatedAt: '2天前',
    isOfficial: true,
    desc: '包含 PRD 模板、用户故事卡、竞品分析框架、设计规范文档。利用小浣熊 PAW 三步法，配合本知识库可快速生成符合团队规范的需求文档。',
    preview: [
      'PRD 需求文档模板 v2.0.docx',
      '用户故事卡模板.md',
      '功能优先级评估矩阵.xlsx',
      'UX 设计规范手册.pdf',
      '竞品分析框架.docx',
      '产品迭代复盘模板.md',
    ],
    usagePattern: '@产品知识库 基于用户反馈，帮我起草「消息通知中心」功能的 PRD，参考现有文档格式',
    linkedChains: ['竞品分析报告生成链路', '用户需求拆解链路'],
    pawSteps: ['Plan：拆解功能需求点', 'Analyze：参考知识库现有 PRD 结构', 'Write：生成完整 PRD 文档'],
  },
  {
    id: '4',
    title: '财务分析与报表解读库',
    industry: '金融',
    tags: ['财务', '报表', '分析', '指标'],
    author: '陈分析师',
    avatar: 'C',
    docCount: 189,
    fileTypes: ['Excel', 'PDF'],
    saves: 1743,
    views: 5840,
    likes: 296,
    createdAt: '2周前',
    updatedAt: '4天前',
    isOfficial: false,
    desc: '包含财务三表解读指南、关键指标计算公式、DCF 估值模型、行业基准对比数据。上传财务报表后，小浣熊可参考本知识库自动生成分析报告。',
    preview: [
      '财务三表快速解读手册.pdf',
      'DCF 估值模型.xlsx',
      '财务指标速查表.xlsx',
      '异常指标预警规则.docx',
      '行业财务基准数据.xlsx',
      '季报撰写规范指引.docx',
    ],
    usagePattern: '@财务知识库 上传的是 Q3 财报，请分析主要财务指标变化趋势并标注异常项',
    linkedChains: ['季报智能分析链路', '财务异常检测链路'],
    pawSteps: ['Plan：确定分析维度（盈利/偿债/运营/成长）', 'Analyze：对比知识库行业基准数据', 'Write：生成含结论的财务分析报告'],
  },
  {
    id: '5',
    title: '电商运营全场景知识库',
    industry: '电商',
    tags: ['选品', '广告', '数据分析', '运营'],
    author: '张小明',
    avatar: 'Z',
    docCount: 243,
    fileTypes: ['Excel', 'PDF', 'Word'],
    saves: 2284,
    views: 9120,
    likes: 502,
    createdAt: '1个月前',
    updatedAt: '2天前',
    isOfficial: true,
    desc: '覆盖选品分析、广告投放、活动策划、数据复盘的完整运营知识体系。配套多条小浣熊链路，可直接用于日报/周报自动生成、广告效果分析。',
    preview: [
      '选品分析 SOP.pdf',
      '广告投放 ROI 计算模板.xlsx',
      '大促活动策划手册.docx',
      '数据日报自动化模板.xlsx',
      '竞品价格监控规则.docx',
      '用户评论情感分析指南.md',
    ],
    usagePattern: '@运营知识库 根据本周销售数据，帮我生成运营周报，重点分析 ROI 下降原因',
    linkedChains: ['销售数据日报链路', '用户评论批量分析链路', '活动效果复盘链路'],
    pawSteps: ['Plan：确定报告周期和数据范围', 'Analyze：参照知识库指标体系解读数据', 'Write：生成图文并茂的运营报告'],
  },
  {
    id: '6',
    title: '医疗文书规范知识库',
    industry: '医疗',
    tags: ['病历', '医嘱', '规范', '临床'],
    author: '王医生',
    avatar: 'W',
    docCount: 128,
    fileTypes: ['PDF', 'Word'],
    saves: 912,
    views: 3450,
    likes: 198,
    createdAt: '3周前',
    updatedAt: '5天前',
    isOfficial: false,
    desc: '收录病历书写规范、常见病诊疗路径、医嘱模板、知情同意书等临床文书。转存后可让小浣熊参考规范自动结构化病历文本，节省医生书写时间。',
    preview: [
      '病历书写质控标准.pdf',
      '常见疾病诊疗路径.pdf',
      '手术知情同意书模板.docx',
      '护理记录书写规范.docx',
      '药物使用说明速查.pdf',
      '出院小结模板.docx',
    ],
    usagePattern: '@医疗知识库 将以下口述病历内容整理为符合规范的电子病历格式',
    linkedChains: ['病历结构化提取链路', '出院小结生成链路'],
    pawSteps: ['Plan：识别病历关键信息字段', 'Analyze：对照书写规范检查完整性', 'Write：输出结构化标准病历'],
  },
  {
    id: '7',
    title: '代码审查与研发规范库',
    industry: '互联网',
    tags: ['代码规范', '安全', 'Code Review', '研发'],
    author: '技术负责人',
    avatar: 'T',
    docCount: 156,
    fileTypes: ['Markdown', 'PDF'],
    saves: 1654,
    views: 6320,
    likes: 334,
    createdAt: '2周前',
    updatedAt: '1天前',
    isOfficial: false,
    desc: '包含前后端编码规范、安全漏洞检查项、Code Review 评审标准、API 设计指南。小浣熊代码模式下 @ 本库，可自动对照规范完成代码审查。',
    preview: [
      '前端编码规范 v3.0.md',
      '后端 API 设计指南.md',
      '安全漏洞检查清单（OWASP）.pdf',
      'Code Review 评审标准.md',
      'SQL 查询优化规范.md',
      '单元测试覆盖率要求.md',
    ],
    usagePattern: '@研发规范库 对这段 Python 代码做 Code Review，重点检查安全问题和规范符合性',
    linkedChains: ['代码安全扫描链路', 'PR 自动评审链路'],
    pawSteps: ['Plan：明确审查维度（安全/性能/规范）', 'Analyze：逐条对照规范文档检查', 'Write：生成评审意见和改进建议'],
  },
  {
    id: '8',
    title: '市场营销内容素材库',
    industry: '通用',
    tags: ['营销', '文案', '品牌', '内容创作'],
    author: '市场团队',
    avatar: 'M',
    docCount: 312,
    fileTypes: ['Word', 'Markdown', 'PDF'],
    saves: 1834,
    views: 7640,
    likes: 428,
    createdAt: '1周前',
    updatedAt: '12小时前',
    isOfficial: true,
    desc: '汇集品牌手册、文案风格指南、历史爆款案例、各渠道内容模板。转存后让小浣熊参考品牌调性自动生成符合风格的营销内容，保持品牌一致性。',
    preview: [
      '品牌视觉与文案风格指南.pdf',
      '微信公众号推文模板集.docx',
      '小红书种草文案公式.md',
      '抖音脚本写作框架.docx',
      '历史爆款案例分析.xlsx',
      '活动策划文案模板库.docx',
    ],
    usagePattern: '@营销知识库 参考品牌风格，为新品发布写一篇小红书种草文案，突出 AI 办公场景',
    linkedChains: ['多平台内容批量生成链路', '爆款文案分析链路'],
    pawSteps: ['Plan：确定目标平台和受众', 'Analyze：参考知识库爆款案例和品牌调性', 'Write：生成符合平台规范的营销内容'],
  },
]

export type KB = typeof ALL_KBS[0]
