#!/bin/bash

echo "🦝 推送小浣熊项目到 GitHub"
echo "================================"
echo ""
echo "仓库: https://github.com/Sapesn/Raccon-Comm"
echo ""
echo "请按照以下步骤操作："
echo ""
echo "方法 1: 使用 GitHub Token (推荐)"
echo "--------------------------------"
echo "1. 访问 https://github.com/settings/tokens"
echo "2. 点击 'Generate new token' -> 'Generate new token (classic)'"
echo "3. 勾选 'repo' 权限"
echo "4. 生成 token 并复制"
echo ""
echo "然后执行以下命令（替换 YOUR_TOKEN）："
echo "  cd /Users/asui/raccoon-kb-mvp"
echo "  git remote set-url origin https://YOUR_TOKEN@github.com/Sapesn/Raccon-Comm.git"
echo "  git push -u origin main"
echo ""
echo ""
echo "方法 2: 使用 SSH (更简单)"
echo "--------------------------------"
echo "执行以下命令："
echo ""
echo "  cd /Users/asui/raccoon-kb-mvp"
echo "  git remote set-url origin git@github.com:Sapesn/Raccon-Comm.git"
echo "  git push -u origin main"
echo ""
echo "如果提示 SSH key 问题，运行："
echo "  ssh-keygen -t ed25519 -C 'your_email@example.com'"
echo "  cat ~/.ssh/id_ed25519.pub"
echo "然后将输出的公钥添加到 GitHub: https://github.com/settings/keys"
echo ""
